services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/secrets/settings.env
    volumes:
      - ./Backend:/app

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
